-- MySQL Script generated by MySQL Workbench
-- Fri Aug 12 00:18:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema peluqueria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `peluqueria` ;

-- -----------------------------------------------------
-- Schema peluqueria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peluqueria` DEFAULT CHARACTER SET utf8mb4 ;
USE `peluqueria` ;

-- -----------------------------------------------------
-- Table `peluqueria`.`dueno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peluqueria`.`dueno` (
  `dni` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `telefono` INT(11) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `peluqueria`.`perro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peluqueria`.`perro` (
  `id_perro` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `fecha_nac` VARCHAR(100) NOT NULL,
  `sexo` VARCHAR(100) NOT NULL,
  `dni_dueno` INT(11) NOT NULL,
  PRIMARY KEY (`id_perro`),
  CONSTRAINT `perro_ibfk_1`
    FOREIGN KEY (`dni_dueno`)
    REFERENCES `peluqueria`.`dueno` (`dni`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `dni_dueno` ON `peluqueria`.`perro` (`dni_dueno` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `peluqueria`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peluqueria`.`historial` (
  `id_historial` INT(11) NOT NULL,
  `fecha` VARCHAR(100) NOT NULL,
  `perro` INT(11) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`id_historial`),
  CONSTRAINT `historial_ibfk_1`
    FOREIGN KEY (`perro`)
    REFERENCES `peluqueria`.`perro` (`id_perro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `perro` ON `peluqueria`.`historial` (`perro` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
